app:
  host: api-ozensemble.fabrique.social.gouv.fr

cronjobs:
  ~chart: daemon
  ~needs: [build-app]
  imagePackage: app
  replicas: 1
  entrypoint: ["node", "./src/cronjobs.js"]
  envFrom:
    - secretRef:
        name: "pg-user"
    - secretRef:
        name: api
